[theme]
# Primary accent color for interactive elements.
primaryColor = "#4169E1"

# Background color for the main content area
backgroundColor = '#FFFAFA'

# Color used for almost all text.
textColor = "#FFFAFA"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
